### ISSUE TITLE
 security vendors and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by 1234xxcc** [CherryPill/system_info#87]
security vendors and no sandboxes flagged this file as malicious
https://www.virustotal.com/gui/file/c97bec7781487825da96d0fdfba0a7cbd72a7efb08063ddfe112f94af2327be1/detection

**Comment by CherryPill** [comment]
Please refer to https://github.com/CherryPill/system_info/issues/73

In short it's a false positive since the .exe isn't signed, the source code is free for you to explore and compile
